language: node_js

node_js:
- node
- 'lts/*'

env:
  global:
    - IMAGE_NAME=rflpazini/cerebro

install:
  - npm install -g codecov
  - npm install

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - npm update -g npm

script:
  - npm run test:coverage
  - npm run lint
  - docker build --tag "$IMAGE_NAME" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - TAG="$(git log -1 --pretty=%h)"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TAG}"


deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TAG}"
  on:
    branch: master
