language: node_js

node_js:
- node
- 'lts/*'

install:
  - npm install -g codecov
  - npm install

cache:
  directories:
    - node_modules

before_install:
  - npm update -g npm

script:
  - npm run test
  - npm run lint
  - npm run test:coverage